Repository bmw-software-engineering/trlc, pull requests merged in 2024-10, with the labels that each got.

#108 fixes python3.8 disabled error
  .github/workflows/ci.yml
Labels: bug, CI

#111 specifies github runner images explicitly
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/package.yml
Labels: CI

#109 Implement review comments from PR #66
  tests-system/rbt-endswith-semantics/foo.trlc
  tests-system/rbt-endswith-semantics/output
  tests-system/rbt-endswith-semantics/output.brief
  tests-system/rbt-endswith-semantics/output.json
  tests-system/rbt-endswith-semantics/output.smtlib
  tests-system/rbt-len-semantics/foo.rsl
  tests-system/rbt-len-semantics/foo.trlc
  tests-system/rbt-len-semantics/output.json
  tests-system/rbt-matches-semantics/foo.rsl
  tests-system/rbt-matches-semantics/foo.trlc
  tests-system/rbt-matches-semantics/output
  tests-system/rbt-matches-semantics/output.brief
  tests-system/rbt-matches-semantics/output.json
  tests-system/rbt-matches-semantics/output.smtlib
  tests-system/rbt-signature-len-1/foo.rsl
  tests-system/rbt-signature-len-1/output
  tests-system/rbt-signature-len-1/output.brief
  tests-system/rbt-signature-len-1/output.json
  tests-system/rbt-signature-len-1/output.smtlib
  tests-system/rbt-signature-len-2/foo.rsl
  tests-system/rbt-signature-len-2/foo.trlc
  tests-system/rbt-signature-len-2/output
  tests-system/rbt-signature-len-2/output.brief
  tests-system/rbt-signature-len-2/output.json
  tests-system/rbt-signature-len-2/output.smtlib
  tests-system/rbt-signature-matches-1/foo.rsl
  tests-system/rbt-signature-matches-1/output
  tests-system/rbt-signature-matches-1/output.brief
  tests-system/rbt-signature-matches-1/output.json
  tests-system/rbt-signature-matches-1/output.smtlib
  tests-system/rbt-signature-matches-2/foo.rsl
  tests-system/rbt-signature-matches-2/foo.trlc
  tests-system/rbt-signature-matches-2/output
  tests-system/rbt-signature-matches-2/output.brief
  tests-system/rbt-signature-matches-2/output.json
  tests-system/rbt-signature-matches-2/output.smtlib
  tests-system/rbt-signature-matches-3/foo.rsl
  tests-system/rbt-signature-matches-3/output
  tests-system/rbt-signature-matches-3/output.json
  tests-system/rbt-signature-matches-3/output.smtlib
  tests-system/rbt-signature-string-end-functions-1/foo.rsl
  tests-system/rbt-signature-string-end-functions-1/output
  tests-system/rbt-signature-string-end-functions-1/output.brief
  tests-system/rbt-signature-string-end-functions-1/output.json
  tests-system/rbt-signature-string-end-functions-1/output.smtlib
  tests-system/rbt-signature-string-end-functions-2/foo.rsl
  tests-system/rbt-signature-string-end-functions-2/foo.trlc
  tests-system/rbt-signature-string-end-functions-2/output
  tests-system/rbt-signature-string-end-functions-2/output.brief
  tests-system/rbt-signature-string-end-functions-2/output.json
  tests-system/rbt-signature-string-end-functions-2/output.smtlib
  tests-system/rbt-signature-string-end-functions-3/foo.rsl
  tests-system/rbt-signature-string-end-functions-3/output
  tests-system/rbt-signature-string-end-functions-3/output.brief
  tests-system/rbt-signature-string-end-functions-3/output.json
  tests-system/rbt-signature-string-end-functions-3/output.smtlib
Labels: CI

#112 adds one status check job
  .github/workflows/ci.yml
Labels: CI

#115 Add clause "simplified name" to LRM
  language-reference-manual/lrm.trlc
Labels: topic: LRM
