Repository bmw-software-engineering/trlc, pull requests merged in 2025-03, with the labels that each got.

#131 Supports python 3.13
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  documentation/TUTORIAL-INSTALL.md
  documentation/dev_setup.md
  setup.py
Labels: CI

#133 Update author e-mail in `setup.py`
  setup.py
Labels: documentation

#132 adds linter warnings on unused imports
  CHANGELOG.md
  tests-system/late-packages-2/output
  tests-system/late-packages-2/output.smtlib
  tests-system/rbt-late-package-declarations/output
  tests-system/rbt-late-package-declarations/output.smtlib
  trlc/lint.py
  trlc/trlc.py
Labels: topic: analysis
